Github-actions -- integrating es-bundle in a loop

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -52,11 +52,11 @@ jobs:
           docker run -d \
             --name elasticsearch \
             -v elasticsearch:/usr/share/elasticsearch/data \
-            -p 9200:9200 \ 
+            -p 9200:9200 \
             -p 9300:9300 \
             -e "ES_JAVA_OPTS=-Xmx256m -Xms256m" \
             -e "ELASTIC_USERNAME=elastic" \
-            -e "ELASTIC_PASSWORD=changeme" \  
+            -e "ELASTIC_PASSWORD=changeme" \
             -e "discovery.type=single-node" \
             --health-cmd="curl --silent --fail http://localhost:9200/_cluster/health || exit 1" \
             --health-interval=30s \
@@ -65,62 +65,31 @@ jobs:
             --restart=on-failure \
             elasticsearch:${{ env.SHA }}
 
-      - name: Start Logstash
+      # Wait for Elasticsearch and test the endpoint
+      - name: Check cluster health
         run: |
-          docker run -d --name logstash \
-            -p 5044:5044 \
-            -p 5000:5000/tcp \
-            -p 5000:5000/udp \
-            -p 9600:9600 \
-            -e LS_JAVA_OPTS="-Xmx256m -Xms256m" \
-            --restart=on-failure \
-            logstash:${{ env.SHA }}
+          sleep 25
 
-      - name: Start Kibana
+          status_code=$(curl -u elastic:changeme --write-out '%{http_code}' --silent --output /dev/null http://localhost:9200/_cluster/health)
+          echo "Elasticsearch health check returned status $status_code"
+
+          if [ "$status_code" != "200" ]; then
+            echo "Error: Elasticsearch health check failed with status $status_code"
+            exit 1
+          fi
+      # -----------------------------------
+      # Log into Docker Hub
+      - name: Log into Docker Hub
+        uses: docker/login-action@v1
+        with:
+          username: ${{ secrets.DOCKER_HUB_USERNAME }}
+          password: ${{ secrets.DOCKER_HUB_TOKEN }}
+
+      # Push the image to Docker Hub
+      - name: Push ${{ matrix.es-bundle.name }}
         run: |
-          docker run -d --name kibana \
-            -p 5601:5601 \
-            --link elasticsearch:elasticsearch \
-            --network search-engine \
-            --restart on-failure \  
-            kibana:${{ env.SHA }}
-
-      - name: Start Filebeat
-        run: |
-          docker run -d --name filebeat \
-            --volume "/var/lib/docker/containers:/usr/share/filebeat/dockerlogs:ro" \
-            --volume "/var/run/docker.sock:/var/run/docker.sock" \
-            --link elasticsearch:elasticsearch \ 
-            --link kibana:kibana \
-            --network search-engine \
-            --restart on-failure \
-            filebeat:${{ env.SHA }} \
-            filebeat -e --strict.perms=false
-      # # Wait for Elasticsearch and test the endpoint
-      # - name: Check cluster health
-      #   run: |
-      #     sleep 25
-
-      #     status_code=$(curl -u elastic:changeme --write-out '%{http_code}' --silent --output /dev/null http://localhost:9200/_cluster/health)
-      #     echo "Elasticsearch health check returned status $status_code"
-
-      #     if [ "$status_code" != "200" ]; then
-      #       echo "Error: Elasticsearch health check failed with status $status_code"
-      #       exit 1
-      #     fi
-      # # -----------------------------------
-      # # Log into Docker Hub
-      # - name: Log into Docker Hub
-      #   uses: docker/login-action@v1
-      #   with:
-      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
-      #     password: ${{ secrets.DOCKER_HUB_TOKEN }}
-
-      # # Push the image to Docker Hub
-      # - name: Push ${{ matrix.es-bundle.name }}
-      #   run: |
-      #     IMAGE_NAME=${{ matrix.es-bundle.name }}
-      #     IMAGE_TAG=${{ env.SHA }}
-      #     IMAGE_ID=docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME
-      #     docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_ID:$IMAGE_TAG
-      #     docker push $IMAGE_ID:$IMAGE_TAG
+          IMAGE_NAME=${{ matrix.es-bundle.name }}
+          IMAGE_TAG=${{ env.SHA }}
+          IMAGE_ID=docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME
+          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_ID:$IMAGE_TAG
+          docker push $IMAGE_ID:$IMAGE_TAG
