Github-actions -- integrating es-bundle in a loop

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -54,36 +54,36 @@ jobs:
 
       # Start the Elasticsearch container
       # --------------------------------------------------------------------------------
-      - name: Start Elasticsearch
-        run: |
-          docker run -d \
-            --name elasticsearch \
-            -v elasticsearch:/usr/share/elasticsearch/data \
-            -p 9200:9200 \
-            -p 9300:9300 \
-            -e "ES_JAVA_OPTS=-Xmx256m -Xms256m" \
-            -e "ELASTIC_USERNAME=elastic" \
-            -e "ELASTIC_PASSWORD=changeme" \
-            -e "discovery.type=single-node" \
-            --health-cmd="curl --silent --fail http://localhost:9200/_cluster/health || exit 1" \
-            --health-interval=30s \
-            --health-timeout=30s \
-            --health-retries=5 \
-            --restart=on-failure \
-            elasticsearch:${{ env.SHA }}
+      # - name: Start Elasticsearch
+      #   run: |
+      #     docker run -d \
+      #       --name elasticsearch \
+      #       -v elasticsearch:/usr/share/elasticsearch/data \
+      #       -p 9200:9200 \
+      #       -p 9300:9300 \
+      #       -e "ES_JAVA_OPTS=-Xmx256m -Xms256m" \
+      #       -e "ELASTIC_USERNAME=elastic" \
+      #       -e "ELASTIC_PASSWORD=changeme" \
+      #       -e "discovery.type=single-node" \
+      #       --health-cmd="curl --silent --fail http://localhost:9200/_cluster/health || exit 1" \
+      #       --health-interval=30s \
+      #       --health-timeout=30s \
+      #       --health-retries=5 \
+      #       --restart=on-failure \
+      #       elasticsearch:${{ env.SHA }}
 
-      # Wait for Elasticsearch and test the endpoint
-      - name: Check cluster health
-        run: |
-          sleep 25
+      # # Wait for Elasticsearch and test the endpoint
+      # - name: Check cluster health
+      #   run: |
+      #     sleep 25
 
-          status_code=$(curl -u elastic:changeme --write-out '%{http_code}' --silent --output /dev/null http://localhost:9200/_cluster/health)
-          echo "Elasticsearch health check returned status $status_code"
+      #     status_code=$(curl -u elastic:changeme --write-out '%{http_code}' --silent --output /dev/null http://localhost:9200/_cluster/health)
+      #     echo "Elasticsearch health check returned status $status_code"
 
-          if [ "$status_code" != "200" ]; then
-            echo "Error: Elasticsearch health check failed with status $status_code"
-            exit 1
-          fi
+      #     if [ "$status_code" != "200" ]; then
+      #       echo "Error: Elasticsearch health check failed with status $status_code"
+      #       exit 1
+      #     fi
       # -----------------------------------
       # Log into Docker Hub
       - name: Log into Docker Hub
